### ISSUE TITLE
MissingMethodException running Chart.toSVGString using Plotly.Net.ImageExport

### ISSUE THREAD

**Issue by Altariarite** [plotly/Plotly.NET#361]
Calling `Chart.toSVGString` gives me:
```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Puppeteer.LaunchAsync(PuppeteerSharp.LaunchOptions, Microsoft.Extensions.Logging.ILoggerFactory)'.
   at <StartupCode$Plotly-NET-ImageExport>.$PuppeteerSharpRenderer.clo@83-16.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1167
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511
   at <StartupCode$myApp>.$Program.main@() in C:\Users\altaria\fsharp\Valueline\myApp\Program.fs:line 44
```
My code snippet:
``` fsharp
// Api.chart is a GenericChart
open Giraffe.ViewEngine
let chartView = Api.chart |> Chart.toSVGString (Width = 800, Height = 600) |> Text
```

It looks like there's some issue calling a Puppeteer function?
I am on .NET 6 and running `dotnet watch`. I've tried PuppeteerSharp version 8.0.0 and 6.0.0 with no success.

**Comment by Altariarite** [comment]
I managed to get it running by doing `paket add NETStandard.Library --version 2.0.3` after seeing [this post](https://stackoverflow.com/questions/62284301/method-not-found-system-threading-tasks-task10) on StackOverflow. Maybe I am missing something obvious here...
